services:
  anvil-uplink:
    container_name: anvil-uplink
    image: my-anvil-app
    restart: always
    network_mode: "host"
    volumes:
      - ./models:/app/models
    environment:
      - ANVIL_UPLINK_KEY=server_5GREDJABFF3PRT4ABWNTTYVV-W6WI735Y5M6XCIOE
